budgme/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.contrib import admin
from django.views.generic.base import RedirectView

from django.contrib.auth.views import login, logout,\
    password_change, password_change_done

from datetime import datetime
from budgme import views
from budgme.forms import CustomAuthenticationForm, CustomPasswordChangeForm
from django.utils.translation import ugettext_lazy as _

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login$', login,
        {
            'template_name': 'budgme/login.html',
            'authentication_form': CustomAuthenticationForm,
            'extra_context':
                {
                    'title': _('Login, please'),
                    'year': datetime.now().year,
                }
        }, name='login'),
    url(r'^logout$', logout,
        {
            'next_page': '/login'
        }, name='logout'),
    url(r'^password_change/$', password_change,
        {
            'template_name': 'budgme/password_change.html',
            'password_change_form': CustomPasswordChangeForm,
            'extra_context':
                {
                    'title': _('You can change your password')
                }
        }, name='password_change'),
    url(r'^password_change/done/$', password_change_done,
        {
            'template_name': 'app/password_change_done.html',
        }, name='password_change_done'),

    # home pages
    url(r'^$', views.MasterPage.as_view(), name='home'),
    url(r'^home$', views.MasterPage.as_view(), name='index'),
    url(r'^ajax/$', views.AJAXRenderer.as_view(), name='ajax_home'),

    # profile pages
    url(r'^profile$', views.MasterPage.as_view(), name='profile'),
    url(r'^ajax/profile$', views.AJAXRenderer.as_view(), name='ajax_profile'),

    # income category pages
    url(r'^income-categories$', views.MasterPage.as_view(), name='income_categories'),
    url(r'^ajax/income-categories$', views.AJAXRenderer.as_view(), name='ajax_income_categories'),
    url(r'^ajax/add-in-cat$', views.AJAXRenderer.as_view(), name='ajax_add_in_cat'),
    url(r'^ajax/edit-in-cat$', views.AJAXRenderer.as_view(), name='ajax_edit_in_cat'),
    url(r'^ajax/del-in-cat$', views.AJAXRenderer.as_view(), name='ajax_del_in_cat'),
    url(r'^ajax/force-del-in-cat$', views.AJAXRenderer.as_view(), name='ajax_force_del_in_cat'),

    # budget pages
    url(r'^ajax/change_budget$', views.AJAXRenderer.as_view(), name='ajax_change_budget'),

    # url(r'^.*$', RedirectView.as_view(url='/', permanent=False), name='index'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if not settings.DEBUG:
#     urlpatterns += static('',
#         (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
#     )

budgme/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

from budgme import models

User = get_user_model()

class CustomAuthenticationForm(AuthenticationForm):
    """Authentication form which uses bootstrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': _('login or email')}))
    password = forms.CharField(label=_(u"Ваш пароль"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder': _('password')}))


class CustomPasswordChangeForm(PasswordChangeForm):
    """
    A custom form that lets a user change their password by entering their old
    password.
    """
    old_password = forms.CharField(label=_('Current password'),
                                   widget=forms.PasswordInput(
                                       {
                                           'class': 'form-control',
                                           'placeholder': _('current password')
                                       }
                                   ))
    new_password1 = forms.CharField(label=_('new password'),
                                    widget=forms.PasswordInput(
                                        {
                                            'class': 'form-control',
                                            'placeholder': _('new password')
                                        }
                                    ))
    new_password2 = forms.CharField(label=_('repeat new password'),
                                    widget=forms.PasswordInput({
                                        'class': 'form-control',
                                        'placeholder': _('new password again')
                                    }))


class IncomeCategoryForm(forms.ModelForm):
    class Meta:
        model = models.IncomeCategory
        fields = [
            'id',
            'name',
            'description',
        ]

budgme/views.py
# -*- coding: utf-8 -*-
"""
Definition of views.
"""

# import os
# import codecs
# import copy

from django.shortcuts import render
from django.http import HttpRequest, HttpResponseRedirect, HttpResponse
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.views import View
from django.views.generic import TemplateView, ListView, FormView
from django.shortcuts import get_object_or_404

from django.contrib.auth.models import Group

from django.core.exceptions import ObjectDoesNotExist
# from django.template import RequestContext

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Q


from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext as __
from django.utils.translation import activate, get_language_info
from django_ajax.mixin import AJAXMixin
# from django_ajax.decorators import ajax

# from budgme.models import Budget, IncomeCategory, Profile
from budgme import models
from budgme import forms

# AJAX_DECORATORS = [
#     login_required,
#     ajax,
# ]


def get_current_budget(request):
    """This method return current budget object for current user
    based on session cookies
    NOTE! this method hits DB on each call
    Use get_current_budget_name method if you need only name, not object"""
    budget = request.session.get('budget')
    if not budget:
        budget = models.Profile.objects.get(user=request.user).default_budget
        request.session['budget'] = budget.name
    else:
        budget = models.Budget.objects.filter(
            Q(owner=request.user) & Q(name=budget)).first()
    return budget


def get_current_budget_name(request):
    """This method doing the same as get_current_budget method
    except it querying the database only if current_budget value
    is not set yet for current session"""
    budget = request.session.get('budget')
    if not budget:
        budget = models.Profile.objects.get(user=request.user).default_budget
        request.session['budget'] = budget.name
        budget = budget.name
    return budget


# Bootstrap sizes according to it's grid system
XS_SIZE = 768
MD_SIZE = 992
LG_SIZE = 1200


def get_grid_size(request):
    """This method parses client size window based on
    bootstrap grid system and returns one of the string:
    'xs' - if width < 768px
    'sm' - if width >= 768px
    'md' - if width >= 992px
    'lg' - if width >= 1200px
    default is 'lg'
    """
    try:
        width = int(request.GET.get('width'))
    except:
        return 'lg'
    else:
        if width >= LG_SIZE:
            return 'lg'
        elif width >= MD_SIZE:
            return 'md'
        elif width >= XS_SIZE:
            return 'sm'
        else:
            return 'xs'


def profile(request):
    return render(request, 'budgme/profile.html')


class MasterPage(LoginRequiredMixin, TemplateView):
    template_name = 'budgme/master.html'

    def get_context_data(self, **kwargs):
        current_budget = get_current_budget(self.request)
        return {
            'current_budget': current_budget,
            'budget_list': models.Budget.objects.filter(
                Q(owner=self.request.user) & ~Q(id=current_budget.id) &
                Q(is_active=True)),
            'shared_budgets': models.BudgetAccess.objects.select_related(
                'budget').filter(Q(target_user=self.request.user) &
                                 ~Q(budget=current_budget)),
        }


class BaseAjaxRenderer:
    def __init__(self):
        """Any content passed in response must be a
        list of tuple(selector, content)"""
        self.replace_content = None
        self.inner_content = None
        self.append_content = None
        self.prepend_content = None

        self.response = {
            'fragments': {
                # 'replace element with this content'
                # self.replace_content goes here
            },
            'inner-fragments': {
                # 'replace inner content'
                # self.inner_content goes here
            },
            'append-fragments': {
                # 'append this content'
                # self.append_content goes here
            },
            'prepend-fragments': {
                # 'prepend this content'
                # self.prepend_content goes here
            },
        }


class BudgetViews(BaseAjaxRenderer):
    """All Get & Post CRUD operations for budget urls
    and change current budget operation"""
    def ajax_change_budget(self):
        current_budget = get_current_budget_name(self.request)
        new_budget = self.request.POST.get('budget')
        if new_budget and current_budget != new_budget:
            self.request.session['budget'] = new_budget


class IncomeCategoryViews(BaseAjaxRenderer):
    """All Get & Post CRUD operations for income categories urls"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.form = forms.IncomeCategoryForm

    def ajax_income_categories(self):

        def get_queryset(request):
            budget = get_current_budget(request)
            return models.IncomeCategory.objects.filter(budget=budget,
                                                        is_active=True)

        context = {
            'object_list': get_queryset(self.request),
            'grid_size': get_grid_size(self.request),
            'page_script': 'budgme/js/in_cat.js',
        }
        self.inner_content = [
            ('#main-container', render(self.request,
                                       'budgme/income/in_cat.html', context)),
            ('#page_script', render(self.request,
                                    'budgme/page_script.html', context)),
        ]

    def ajax_edit_in_cat(self):
        form = self.form(self.request.POST)
        if form.is_valid():
            if not self._name_unique(form.cleaned_data.get('name')):
                return
            try:
                category = models.IncomeCategory.objects.get(
                    id=self.request.POST['id'], budget=self.budget)
            except ObjectDoesNotExist:
                self._fail_popover(msg=__('Can not find this category in DB!'))
                return

            for field in form.cleaned_data:
                setattr(category, field, form.cleaned_data.get(field))
            category.save()
            self._success_popover()
        else:
            self._fail_popover(msg=form.errors.as_text())

    def ajax_add_in_cat(self):
        form = self.form(self.request.POST)
        if form.is_valid():
            if not self._name_unique(form.cleaned_data.get('name')):
                return
            category = models.IncomeCategory(
                budget=self.budget,
                name=form.cleaned_data.get('name'),
                description=form.cleaned_data.get('description'))
            try:
                category.save()
            except Exception as why:
                self._fail_popover(msg=str(why))
                return
            else:
                row_context = {
                    'income_category': category,
                }
                self.append_content = [
                    ("table#table-in_cat>tbody",
                     render(self.request,
                            'budgme/income/in_cat_row.html',
                            row_context)),
                ]
                self._success_popover(msg=__('New income source added'))
                self.response.update({'id': category.id})
        else:
            self._fail_popover(title=__('Failed to add new resource!'),
                               msg=form.errors.as_text())

    def ajax_del_in_cat(self):
        category, budget = self._get_category_and_budget()
        if not category:
            self._fail_popover(
                title=__('Failed to delete category'),
                msg=__('No such category found'))
            return
        incomes = models.Income.objects.filter(budget=budget,
                                               category=category)
        incomes_count = len(incomes)
        if incomes_count > 0:
            msg = __('You have related incomes (' + str(incomes_count) + ') '
                     'on this category that will be lost!\n') + \
                  __('Are you sure you want to continue?')
            self._fail_popover(msg=msg)
            return

        try:
            category.delete()
        except Exception as why:
            self._fail_popover(msg=str(why))
        else:
            self._success_popover(
                msg=__('Income source deleted from your budget!'))

    def ajax_force_del_in_cat(self):
        category, budget = self._get_category_and_budget()
        if not category:
            self._fail_popover(
                title=__('Failed to delete category'),
                msg=__('No such category found'))
            return
        incomes = models.Income.objects.filter(budget=budget,
                                               category=category)
        incomes_count = len(incomes)
        if incomes_count > 0:
            category.is_active = False
            category.save()
        else:
            # just deleting this category from DB
            category.delete()
        self._success_popover(
            msg=__('Income source deleted from your budget!'))

    def _get_category_and_budget(self):
        """Trhis method return category object from DB based on
        POST['id'] and current budget for current user"""
        income_id = self.request.POST.get('id')
        budget = get_current_budget(self.request)
        try:
            category = models.IncomeCategory.objects.get(budget=budget,
                                                         id=income_id)
        except models.IncomeCategory.DoesNotExist:

budgme/templates/budgme/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  {% block meta_tags %}{% endblock %}
  {% block title %}
    <title>Bootstrap 101 Template</title>
  {% endblock %}

    <!-- Bootstrap -->
{#    local bootstrap #}
{#    <link href="{% static 'budgme/bootstrap3.3.7/css/bootstrap.min.css' %}" rel="stylesheet">#}

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% block body %}{% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
{#    local bootstrap js #}
{#    <script src="{% static 'budgme/bootstrap3.3.7/js/bootstrap.min.js' %}"></script>#}

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

budgme/templates/budgme/budget_selector.html
<select id="budget-selector" class="selectpicker show-menu-arrow show-tick"
        data-style="btn-warning btn-rectangle" data-width="fit">
    <option value="{{ current_budget.name }}"
            data-content="<i class='fa {{ current_budget.icon }} fa-fw' aria-hidden='true'></i>&nbsp;{{ current_budget.name }}"></option>

    {# test shared budgets #}
    <option data-content="<i class='fa fa-home fa-fw' aria-hidden='true'></i>&nbsp; Test shared &nbsp;<span class='label label-info'><i class='fa fa-share-alt' aria-hidden='true'></i>&nbsp; shared</span>"
            value="Test shared"></option>

    {# own budgets #}
    {% for budget in budget_list %}
        <option value="{{ budget.name }}"
            data-content="<i class='fa {{ budget.icon }} fa-fw' aria-hidden='true'></i>&nbsp;{{ budget.name }}"></option>
    {% endfor %}

    {# shared budgets #}
    {% for budget_access in shared_budgets %}
        {% with budget=budget_access.budget %}
        <option value="{{ budget.name }}"
                data-content="<i class='fa {{ budget.icon }} fa-fw' aria-hidden='true'></i>&nbsp; {{ budget.name }} &nbsp;
                <span class='label label-info'>
                <i class='fa fa-share-alt' aria-hidden='true'></i>&nbsp; shared
                </span>"></option>
        {% endwith %}
    {% endfor %}
</select>

budgme/templates/budgme/home.html
{% extends "budgme/master.html" %}
{% load staticfiles %}

{% block content %}
    <div class="jumbotron">
      <div class="container" style="text-align: center;">
        <h1>Welcome to Budgme!</h1>
        <p>To continue you should login or register your free anonymous account.</p>
        <p><a class="btn btn-primary btn-lg" href="{% url 'login' %}" role="button">Login</a> or <a class="btn btn-primary btn-lg" href="/register" role="button">Register</a></p>
      </div>
    </div>
{% endblock %}

budgme/templates/budgme/loader-animation.html
<div id="loader-animation">
  <div class="lds-css ng-scope" style="position: absolute; left: calc(50% - 85px);">
      <div style="width:100%;height:100%" class="lds-wedges">
        <div>
          <div>
            <div></div>
          </div>
          <div>
            <div></div>
          </div>
          <div>
            <div></div>
          </div>
          <div>
            <div></div>
          </div>
        </div>
      </div>
  </div>
</div>

budgme/templates/budgme/login.html
{% extends "budgme/master.html" %}
{% load i18n %}

{% block content %}

<div class="row text-center">
    <div class="col-md-6 col-md-offset-3">
        <h2>{{ title }}</h2>
        <h4>{% trans "Use your login or email and password" %}</h4>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-md-4 col-md-offset-3">
        <section id="loginForm">
            <form action="{% url 'login' %}" method="post" class="form-horizontal">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_username" class="col-md-2
                    control-label">{% trans "Login" %}</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2
                    control-label">{% trans "Password" %}</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="{{ next }}" />
                        <input type="submit" value="{% trans "Login" %}" class="btn
                         btn-lg btn-primary btn-block" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">{% trans "Please enter a correct user name and password" %}</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-2" style="text-align: center;">
        {% load staticfiles %}
        <img src="{% static 'budgme/budgme_logo_big.png' %}" class="img-circle" style="width: 160px;">
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'budgme/js/jquery.validate.min.js' %}"></script>

{% endblock %}

budgme/templates/budgme/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
      <title>Budgme! Lead your budget easily</title>
      {% load staticfiles %}
      <!-- Bootstrap -->
      <link rel="stylesheet" type="text/css" href="{% static 'budgme/flaty/bootstrap.min.css' %}">
      <!-- Custom -->
      <link rel="stylesheet" type="text/css" href="{% static 'budgme/css/load_animation.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'budgme/css/custom.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'budgme/css/glyphicon_animate_rotate_flip.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'budgme/css/bootstrap_circle_button.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'budgme/vertical_tab_menu/vertical_tab_menu.css' %}">

      <!-- font-awesome -->
      <link rel="stylesheet" type="text/css" href="{% static 'budgme/font-awesome-4.7.0/css/font-awesome.css' %}">

      <!-- Bootstrap-select from: https://silviomoreto.github.io/bootstrap-select -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">

      <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
      <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
  </head>
  <body class="container">

      {% if user.is_authenticated %}
          {% include 'budgme/menu/authorized_menu.html' %}
      {% else %}
          {% include 'budgme/menu/unauthorized_menu.html' %}
      {% endif %}

      {% include 'budgme/loader-animation.html' %}

      <div id="main-container">
          {% block content %}{% endblock %}
      </div>

      <div id="scripts">
        {% include 'budgme/scripts.html' %}
        {% block scripts %}{% endblock %}
      </div>
      <div id="page_script">
          <!-- this is mainly only for one script that related to the current page only
          (should be replaced with every page loaded through django-ajax) -->
      </div>
  </body>
</html>

budgme/templates/budgme/page_script.html
{% load staticfiles %}
<script src="{% static page_script %}"></script>

budgme/templates/budgme/password_change.html
{% extends "budgme/master.html" %}

{% block content %}

<div class="row text-center">
    <div class="col-md-8 col-md-offset-2">
        <h2>{{ title }}</h2>
        <h4>Вкажіть, будь ласка, поточний пароль</h4>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-2">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <div class="form-group
                {% if form.old_password.errors %}
                 has-error
                {% endif %}">
                    <label for="id_old_password" class="col-md-6
                    control-label">Поточний пароль</label>
                    <div class="col-md-6">
                        {{ form.old_password }}
                        {% if form.old_password.errors %}
                            <p class="bg-danger">
                                {{ form.old_password.errors }}
                            </p>
                        {% endif %}
                    </div>
                </div>
                <div class="form-group
                {% if form.new_password1.errors %}
                 has-error
                {% endif %}">
                    <label for="id_new_password1" class="col-md-6
                    control-label">новий пароль</label>
                    <div class="col-md-6">
                        {{ form.new_password1 }}
                        {% if form.new_password1.errors %}
                            <p class="bg-danger">
                                {{ form.new_password1.errors }}
                            </p>
                        {% endif %}
                    </div>
                </div>
                <div class="form-group
                {% if form.new_password2.errors %}
                 has-error
                {% endif %}">
                    <label for="id_new_password2" class="col-md-6
                    control-label">новий пароль ще раз</label>
                    <div class="col-md-6">
                        {{ form.new_password2 }}
                        {% if form.new_password2.errors %}
                            <p class="bg-danger">
                                {{ form.new_password2.errors }}
                            </p>
                        {% endif %}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-6 col-md-6">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Змінити" class="btn
                         btn-lg btn-primary btn-block" />
                    </div>
                </div>
            </form>
        </section>
    </div>
    <div class="col-md-2">
        {% load staticfiles %}
        <img src="{% static 'budgme/budgme_logo_big.png' %}" class="img-circle">
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}

budgme/templates/budgme/password_change_done.html
{% extends "budgme/master.html" %}

{% block content %}

<div class="jumbotron text-center">
    <hr/>
    <h1>Ваш пароль успішно змінено</h1>
    <hr/>
</div>
{% endblock %}

budgme/templates/budgme/scripts.html
{% load staticfiles %}
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<!-- La<h3>test</h3> compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script type="text/javascript"
        src="{% static 'budgme/js/jquery.validate.min.js' %}"></script>
<script type="text/javascript"
        src="{% static 'budgme/django_ajax/jquery.ajax.min.js' %}"></script>
<script type="text/javascript"
        src="{% static 'budgme/django_ajax/jquery.ajax-plugin.min.js' %}">
</script>

<script src="{% static 'budgme/js/global_script.js' %}"></script>

<!-- Bootstrap-select from: https://silviomoreto.github.io/bootstrap-select -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/i18n/defaults-*.min.js"></script> <!-- optional translation -->#}